[project]
name = "comfyui-lora-stack-pack"
description = "A custom node pack for multi-LoRA stacking and dynamic weight management"
version = "1.0.0"
dependencies = []
license = { text = "MIT" }

[project.urls]
Repository = "https://github.com/makszlak/ComfyUI_lora_stack_pack"
# Icon = "https://raw.githubusercontent.com/makszlak/ComfyUI_lora_stack_pack/main/icon.png"

[tool.comfy]
PublisherId = "makszlak"
DisplayName = "Lora Stack Pack"
Icon = "https://raw.githubusercontent.com/makszlak/ComfyUI_lora_stack_pack/main/icon.png"
